# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
highlighter: pygments
pygments:true
title: 保罗博客
email: cb_java@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: cbpaul
github_username:  cbpual

# Build settings
markdown: kramdown
encoding: utf-8
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
markdown: kramdown
kramdown:
  input: GFM
